### PR TITLE
change mysql/router resource request/limit via the operator

### PR DESCRIPTION
**Pull request by FANLIYANG-OPS**
I see it （https://bugs.mysql.com/bug.php?id=110095），the operator does not support modifying resource objects . 
But in a production environment, there are some requirements for changing resource objects . so i  have add two func in  operator_cluster_py  to  support the requirement for resource changes .
Thank you .

### CODE REVIEW

**Comment by FANLIYANG-OPS** [comment]
I think I have signed the agreement（OCA），My email is  fanliyang@zsnetwork.com . 
I don't know what to do next ， LOL ...
Thanks

**Comment by FANLIYANG-OPS** [comment]
> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/ Please make sure to include your MySQL bug system user (email) in the returned form. Thanks



> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/ Please make sure to include your MySQL bug system user (email) in the returned form. Thanks

I think I have signed the agreement（OCA），My email is [fanliyang@zsnetwork.com](mailto:fanliyang@zsnetwork.com) .
I don't know what to do next ， LOL ...
Thanks

**Comment by FANLIYANG-OPS** [comment]
> Hi, thank you for submitting this pull request. In order to consider your code we need you to sign the Oracle Contribution Agreement (OCA). Please review the details and follow the instructions at https://oca.opensource.oracle.com/ Please make sure to include your MySQL bug system user (email) in the returned form. Thanks

> Hi , I think I have signed the agreement（OCA），My email is [fanliyang@zsnetwork.com](mailto:fanliyang@zsnetwork.com) .
I don't know what to do next ， LOL ...
Thanks

**Comment by mysql-admin** [comment]
Hi @FANLIYANG-OPS 
Your OCA information was entered wrong. 
PR is re-opened so it can continue being processed (you will be asked to confirm the contribution is under the OCA).
Apologies for the mistake

Thanks for contributing to MySQL
==Omer

**Comment by FANLIYANG-OPS** [comment]
> Hi, thank you for your contribution. Please confirm this code is submitted under the terms of the OCA (Oracle's Contribution Agreement) you have previously signed by cutting and pasting the following text as a comment: "I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it." Thanks

Hi，please close this pull request ， I have already given up ， is too cumbersome  ...

**Pull request closed without merging**
