### PR TITLE
Fix build.sh: shebang MUST be on the first line!

### PR DESCRIPTION
**Pull request by sjmudd**
The `#!/bin/bash` MUST be on the first line.

by adding the copyright notice above the shebang the shell will not be executed correctly.

### CODE REVIEW

**Comment by sjmudd** [comment]
It may be time to modify this to include 2022 in the copyright but I'll leave that up to you to do if appropriate given copyright notices and years tend to be decided/managed by the owners.

**Comment by sjmudd** [comment]
Neither https://github.com/mysql/mysql-operator nor https://dev.mysql.com/doc/mysql-operator/en/ make any comments about how to contribute or provide PRs such as this to this repo.

While I understand my proposed patch is tiny it always helps to have explicit information which clarifies the right way to offer PRs:
- do you need us to explicitly confirm that our patches are provided under the same licence as the mysql-operator code, e.g. the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/ ?
- are there any specific style guides we should follow if we provide a PR, or should we simply attempt to follow the existing structure and style within the repo?

From my perspective I offer my PR under the UPL 1.0 stated above to match existing code.

**Comment by sjmudd** [comment]
Similarly there seems to be no way to provide feedback to you on the code you are developing or how to use it which is unfortunate.

The information provided at https://dev.mysql.com/doc/mysql-operator/en/ mentions forums:
- however there is no mysql-operator forum
- there is a mysqlcommunity.slack.com slack community with multiple MySQL related channels.  It might be nice to create a `#mysql-operator` channel to allow people to discuss the operator you are developing.

**Comment by sjmudd** [comment]
I confirm the code being submitted is offered under the terms of the OCA, and that I am authorized to contribute it.

**Comment by sjmudd** [comment]
So I guess I got my answer to above. The OCA is not quite the same as saying you offer this under the UPL 1.0 so it would be good to clarify this in the documentation for making a PR.

**Comment by sjmudd** [comment]
Note: it would also be good for the bot to provide a link to the OCA and also to the process to set one up if it has not been done before.  Modifying the default comment it emits should be simple enough to do that, and I guess this should apply to all github repos where the mysql-oca-bot is present.

**Comment by mysql-admin** [comment]
Hi @sjmudd 

Thanks for your contribution and feedback. Please note:
* copyright year – we update the year the first time there is an update to the file so seeing files with 2021 or 
    even earlier is expected
* Information about the forum - I will pass the feedback to the development team (thanks for pointing it out)
* Contributing is done under the terms of the OCA, not dependent on the license the code is offered under. 
* Bot link to the OCA - When the bot runs (every six hours) it checks if the person is known and has an OCA signed. 
   If the person doesn't - it displays a message pointing the person to the OCA and to the fact it needs to be signed. 
   If the person is known (has previously signed an OCA), it simply asks to confirm the contribution is under the OCA 
  as was done above. 

Thanks again for contributing to MySQL
==Omer

**Pull request closed without merging**
